@startuml componentView

!include ../src/C4-Component.puml
!include ../src/C4-Container.puml

Header_Component("Component View Example")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Boundary_Container(Boundary_containerA, "Container A") {
    Component(componentA, "Component A", "API", "My description")
    Component(componentB, "Component B", "API", "My description")
    Component(componentC, "Component C", "API", "My description")
    Component_Database(componentD, "Component D", "API", "My description")
    Component_Storage(componentE, "Component E", "API", "My description")
}
Container(containerC2, "Container C", "API", "My description")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(Boundary_containerA, containerC2, "<--")
Relation(componentA, containerC2, "<--")
Relation(componentA, componentC, "..")
Relation(componentB, componentC, "==")

' ----------------------------------------------------
' ----------------------------------------------------

Footer()

@enduml