@startuml containerView

!include ../src/C4-Container.puml
!include ../src/C4-Context.puml

Header_Container("Container View Example", "contextView.svg")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

System_Boundary(Boundary_systemA, "System A") {
    Container(containerA, "Container", "Description", "API", "[[componentView.svg]]")
    Container_Script(containerF, "Script", "Description")
    Container_MicroService(containerJ, "Micro Service")
    Container_Service(containerB, "Service", "Description", "API")
    Container_Database(containerC, "Database", "Description", "API")
    Container_PubSub(containerD, "PubSub", "Description", "API")
    Container_Storage(containerE, "Storage", "Description", "API")
    Container_Config(containerL, "Config file", "Description", "API")
    Application_WebServer(containerK, "Server-side Web Application", "Description", "API")
    System_Package(packageA, "Package name") {
        Application_Web(containerH, "Client-side Web Application", "Description", "API")
        Application_Desktop(containerG, "Application Desktop", "Description", "API")
        Application_Mobile(containerI, "Application mobile", "Description", "API")
    }
}
System_External(systemB, "System B")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(Boundary_systemA, systemB, "<--")
Relation(containerC, systemB, "<--")
Relation(containerA, containerB, "<--")
Relation(containerA, containerC, "..")
Relation(containerB, containerC, "==")

' ----------------------------------------------------
' ----------------------------------------------------

Footer()

@enduml