@startuml contextView

!include ../src/C4-Context.puml

Header_Context("Context View Example")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Person(personA, "Person A", "Description")

System(systemA, "System A", "Description")
System(systemB, "System B")
System_External(systemExt, "System External")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(systemA, systemB, "-RIGHT->", "info")
Relation(systemA, systemExt, "-DOWN->")
Relation(systemB, systemExt, "-DOWN->")

Relation(personA, systemA, "-RIGHT->")

' ----------------------------------------------------
' ----------------------------------------------------

Footer()

@enduml