@startuml contextView

!include ../src/C4-Context.puml

Header_Context("Context View Example")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Person(personA, "Person A")

System(systemA, "System A")
System_External(systemB, "System B")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(systemA, systemB, "-->", "info")
Relation(personA, systemA, "-->")

' ----------------------------------------------------
' ----------------------------------------------------

Footer()

@enduml