@startuml containerView

!include ../src/C4-Container.puml
!include ../src/C4-Context.puml

Header_Container("Container View Example")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Boundary_System(Boundary_systemA, "System A") {
    Container(containerA, "Container", "API", "My description")
    Container_Script(containerF, "Script", "API", "My description")
    Container_MicroService(containerJ, "Micro Service", "API", "My description")
    Container_Service(containerB, "Service", "API", "My description")
    Container_Database(containerC, "Database", "API", "My description")
    Container_PubSub(containerD, "PubSub", "API", "My description")
    Container_Storage(containerE, "Storage", "API", "My description")
    Application_Desktop(containerG, "Application Desktop", "API", "My description")
    Application_Web_ClientSide(containerH, "Client-side Web Application", "API", "My description")
    Application_Web_ServerSide(containerK, "Server-side Web Application", "API", "My description")
    Application_Mobile(containerI, "Application mobile", "API", "My description")
}
System_External(systemB, "System B")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(Boundary_systemA, systemB, "<--")
Relation(containerC, systemB, "<--")
Relation(containerA, containerB, "<--")
Relation(containerA, containerC, "..")
Relation(containerB, containerC, "==")

' ----------------------------------------------------
' ----------------------------------------------------

Footer()

@enduml