@startuml doc.color

!include ../src/common.puml

!define Color_Light(alias, id, value) rectangle "==id\nvalue" <<light>> as alias
skinparam rectangle<<light>> {
    StereotypeFontColor COLOR_GRAY_4
    FontColor COLOR_GRAY_5
    BorderColor COLOR_GRAY_5
    Shadowing false
}

!define Color_Dark(alias, id, value) rectangle "==id\nvalue" <<dark>> as alias
skinparam rectangle<<dark>> {
    StereotypeFontColor COLOR_GRAY_2
    FontColor COLOR_GRAY_1
    BorderColor COLOR_GRAY_1
    Shadowing false
}

LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Color_Light(ALIAS_COLOR_GRAY_1, "COLOR GRAY 1", "#ecf0f1") COLOR_GRAY_1
Color_Light(ALIAS_COLOR_GRAY_2, "COLOR GRAY 2", "#b6c1c5") COLOR_GRAY_2
Color_Light(ALIAS_COLOR_GRAY_3, "COLOR GRAY 3", "#84939c") COLOR_GRAY_3
Color_Dark(ALIAS_COLOR_GRAY_4, "COLOR GRAY 4", "#566775") COLOR_GRAY_4
Color_Dark(ALIAS_COLOR_GRAY_5, "COLOR GRAY 5", "#2c3e50") COLOR_GRAY_5

Color_Light(ALIAS_COLOR_YELLOW_1, "COLOR YELLOW 1", "#fffa6f") COLOR_YELLOW_1
Color_Light(ALIAS_COLOR_YELLOW_2, "COLOR YELLOW 2", "#f8df46") COLOR_YELLOW_2
Color_Light(ALIAS_COLOR_YELLOW_3, "COLOR YELLOW 3", "#f1c40f") COLOR_YELLOW_3

Color_Light(ALIAS_COLOR_ORANGE_1, "COLOR ORANGE 1", "#ffe386") COLOR_ORANGE_1
Color_Light(ALIAS_COLOR_ORANGE_2, "COLOR ORANGE 2", "#f2b24e") COLOR_ORANGE_2
Color_Light(ALIAS_COLOR_ORANGE_3, "COLOR ORANGE 3", "#e67e22") COLOR_ORANGE_3

Color_Light(ALIAS_COLOR_RED_1, "COLOR RED 1", "#ffb99c") COLOR_RED_1
Color_Light(ALIAS_COLOR_RED_2, "COLOR RED 2", "#f87b57") COLOR_RED_2
Color_Light(ALIAS_COLOR_RED_3, "COLOR RED 3", "#eb1e1e") COLOR_RED_3

Color_Light(ALIAS_COLOR_GREEN_1, "COLOR GREEN 1", "#85ffb7") COLOR_GREEN_1
Color_Light(ALIAS_COLOR_GREEN_2, "COLOR GREEN 2", "#5ee594") COLOR_GREEN_2
Color_Light(ALIAS_COLOR_GREEN_3, "COLOR GREEN 3", "#2ecc71") COLOR_GREEN_3

Color_Light(ALIAS_COLOR_TURQUOISE_1, "COLOR TURQUOISE 1", "#93e8ea") COLOR_TURQUOISE_1
Color_Light(ALIAS_COLOR_TURQUOISE_2, "COLOR TURQUOISE 2", "#63d0d3") COLOR_TURQUOISE_2
Color_Light(ALIAS_COLOR_TURQUOISE_3, "COLOR TURQUOISE 3", "#1ab9bc") COLOR_TURQUOISE_3

Color_Light(ALIAS_COLOR_BLUE_1, "COLOR BLUE 1", "#98e1ff") COLOR_BLUE_1
Color_Light(ALIAS_COLOR_BLUE_2, "COLOR BLUE 2", "#65bded") COLOR_BLUE_2
Color_Light(ALIAS_COLOR_BLUE_3, "COLOR BLUE 3", "#3498db") COLOR_BLUE_3

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(ALIAS_COLOR_GRAY_1, ALIAS_COLOR_GRAY_2, "=RIGHT=>")
Relation(ALIAS_COLOR_GRAY_2, ALIAS_COLOR_GRAY_3, "=RIGHT=>")
Relation(ALIAS_COLOR_GRAY_3, ALIAS_COLOR_GRAY_4, "=RIGHT=>")
Relation(ALIAS_COLOR_GRAY_4, ALIAS_COLOR_GRAY_5, "=RIGHT=>")

Relation(ALIAS_COLOR_YELLOW_1, ALIAS_COLOR_GRAY_1, "~UP~")
Relation(ALIAS_COLOR_YELLOW_1, ALIAS_COLOR_YELLOW_2, "=RIGHT=>")
Relation(ALIAS_COLOR_YELLOW_2, ALIAS_COLOR_YELLOW_3, "=RIGHT=>")

Relation(ALIAS_COLOR_ORANGE_1, ALIAS_COLOR_YELLOW_1, "~UP~")
Relation(ALIAS_COLOR_ORANGE_1, ALIAS_COLOR_ORANGE_2, "=RIGHT=>")
Relation(ALIAS_COLOR_ORANGE_2, ALIAS_COLOR_ORANGE_3, "=RIGHT=>")

Relation(ALIAS_COLOR_RED_1, ALIAS_COLOR_ORANGE_1, "~UP~")
Relation(ALIAS_COLOR_RED_1, ALIAS_COLOR_RED_2, "=RIGHT=>")
Relation(ALIAS_COLOR_RED_2, ALIAS_COLOR_RED_3, "=RIGHT=>")

Relation(ALIAS_COLOR_GREEN_1, ALIAS_COLOR_RED_1, "~UP~")
Relation(ALIAS_COLOR_GREEN_1, ALIAS_COLOR_GREEN_2, "=RIGHT=>")
Relation(ALIAS_COLOR_GREEN_2, ALIAS_COLOR_GREEN_3, "=RIGHT=>")

Relation(ALIAS_COLOR_TURQUOISE_1, ALIAS_COLOR_GREEN_1, "~UP~")
Relation(ALIAS_COLOR_TURQUOISE_1, ALIAS_COLOR_TURQUOISE_2, "=RIGHT=>")
Relation(ALIAS_COLOR_TURQUOISE_2, ALIAS_COLOR_TURQUOISE_3, "=RIGHT=>")

Relation(ALIAS_COLOR_BLUE_1, ALIAS_COLOR_TURQUOISE_1, "~UP~")
Relation(ALIAS_COLOR_BLUE_1, ALIAS_COLOR_BLUE_2, "=RIGHT=>")
Relation(ALIAS_COLOR_BLUE_2, ALIAS_COLOR_BLUE_3, "=RIGHT=>")

' ----------------------------------------------------
' ----------------------------------------------------

@enduml