@startuml example.component

!include ../src/C4-Component.puml
!include ../src/C4-Container.puml

Header_Component("Example", "containerView.svg")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Container_Boundary(containerA, "Container A") {
    Component(componentA, "Component A", "Description", "API") COLOR_RED_1
    Component(componentB, "Component B", "Description", "API")
    Component(componentC, "Component C", "Description", "API")
    Component_Database(componentD, "Component D", "Description", "API")
    Component_Storage(componentE, "Component E", "Description", "API")
    Container_Package(packageA, "Package name") {
        Component_PubSub(componentF, "Component F", "Description", "API")
        Component_Config(componentG, "Config file", "Description", "API")
    }
}
Container(containerC2, "Container C", "Description", "API")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(containerA, containerC2, "<--")
Relation(componentA, containerC2, "<--")
Relation(componentA, componentC, "..")
Relation(componentB, componentC, "==")

' ----------------------------------------------------
' ----------------------------------------------------

Footer_Component()

@enduml