@startuml view.context

!include ../src/C4-Context.puml

Header_Context("View Example")
LAYOUT_TOP_DOWN

' ----------------------------------------------------
' Elements
' ----------------------------------------------------

Person(person, "User", "Real client")

System(systemA, "System A", "Awsome software", "[[view.container.svg]]")
System(systemB, "System B")
System_External(systemExt, "External system", "Authorization system")

' ----------------------------------------------------
' Relations
' ----------------------------------------------------

Relation(systemA, systemB, "-RIGHT->", "info")
Relation(systemA, systemExt, "-DOWN->")
Relation(systemB, systemExt, "-DOWN->")

Relation(person, systemA, "-RIGHT->")

Note(systemB, "Work in progress", "bottom")

' ----------------------------------------------------
' ----------------------------------------------------

Footer_Context()

@enduml