@startuml C4-Component

!include "https://github.com/N0N4M3pl/plantuml-C4/master/src/style.puml"
!include "https://github.com/N0N4M3pl/plantuml-C4/master/src/common.puml"

' ----------------------------------------------------
' Document
' ----------------------------------------------------

!definelong Header_Component(text)
left header Component View
title text
!enddefinelong

' ----------------------------------------------------
' Component
' ----------------------------------------------------

!define Boundary_Container(alias, label) rectangle "==label" <<boundary container>> as alias
skinparam rectangle<<boundary container>> {
    StereotypeFontColor FONT_COLOR
    FontColor FONT_COLOR
    BackgroundColor BOUNDARY_CONTAINER_BG_COLOR
    BorderColor BOUNDARY_CONTAINER_BD_COLOR
    BorderStyle dashed
    BorderThickness 1
    Shadowing false
}

!define Component(alias, label, technology=" ", description=" ") component "==label\n [technology]\n //description//" <<component>> as alias
skinparam component<<component>> {
    StereotypeFontColor FONT_COLOR
    FontColor FONT_COLOR
    BackgroundColor COMPONENT_BG_COLOR
    BorderColor COMPONENT_BD_COLOR
    Shadowing false
}

!define Component_Database(alias, label, technology=" ", description=" ") database "==label\n [technology]\n //description//" <<component database>> as alias
skinparam database<<component database>> {
    StereotypeFontColor FONT_COLOR
    FontColor FONT_COLOR
    BackgroundColor COMPONENT_BG_COLOR
    BorderColor COMPONENT_BD_COLOR
    Shadowing false
}

!define Component_Storage(alias, label, technology=" ", description=" ") stack "==label\n [technology]\n //description//" <<component storage>> as alias
skinparam stack<<component storage>> {
    StereotypeFontColor FONT_COLOR
    FontColor FONT_COLOR
    BackgroundColor COMPONENT_BG_COLOR
    BorderColor COMPONENT_BD_COLOR
    Shadowing false
}

' ----------------------------------------------------
' ----------------------------------------------------

@enduml