@startuml C4-Context

' !include style.puml
' !include common.puml
!include https://raw.githubusercontent.com/N0N4M3pl/plantuml-C4/master/src/style.puml
!include https://raw.githubusercontent.com/N0N4M3pl/plantuml-C4/master/src/common.puml

' ----------------------------------------------------
' Document
' ----------------------------------------------------

!definelong Header_Context(text)
title text
!enddefinelong

!definelong Footer_Context()
caption Context View
Footer()
!enddefinelong

' ----------------------------------------------------
' Context
' ----------------------------------------------------

!define System(alias, label, description=" ", link="") node "==label\n //description//" <<system>> as alias link
skinparam node<<system>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_SYSTEM_BG
    BorderColor COLOR_SYSTEM_BD
}

!define System_External(alias, label, description=" ", link="") node "==label\n //description//" <<external system>> as alias link
skinparam node<<external system>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_SYSTEM_EXTERNAL_BG
    BorderColor COLOR_SYSTEM_EXTERNAL_BD
}

' ----------------------------------------------------
' ----------------------------------------------------

@enduml
