@startuml C4-Context

!include style.puml
!include common.puml

' ----------------------------------------------------
' Context
' ----------------------------------------------------

!define System(alias, label) rectangle "==label" <<system>> as alias
skinparam rectangle<<system>> {
    StereotypeFontColor FONT_COLOR
    FontColor FONT_COLOR
    BackgroundColor SYSTEM_BG_COLOR
    BorderColor SYSTEM_BD_COLOR
    Shadowing false
}

!define System_External(alias, label) rectangle "==label" <<system external>> as alias
skinparam rectangle<<system external>> {
    StereotypeFontColor FONT_COLOR
    FontColor FONT_COLOR
    BackgroundColor SYSTEM_EXTERNAL_BG_COLOR
    BorderColor SYSTEM_EXTERNAL_BD_COLOR
    Shadowing false
}

' ----------------------------------------------------
' ----------------------------------------------------

@enduml