@startuml C4-Component

' !include style.puml
' !include common.puml
!include https://raw.githubusercontent.com/N0N4M3pl/plantuml-C4/master/src/style.puml
!include https://raw.githubusercontent.com/N0N4M3pl/plantuml-C4/master/src/common.puml

' ----------------------------------------------------
' Document
' ----------------------------------------------------

!definelong Header_Component(text, link)
left header [[link Back to Container View]]
title text
!enddefinelong

!definelong Footer_Component()
caption Component View
Footer()
!enddefinelong

' ----------------------------------------------------
' Component
' ----------------------------------------------------

!define Container_Boundary(alias, label) rectangle "==label" <<container boundary>> as alias
skinparam rectangle<<container boundary>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_BOUNDARY_CONTAINER_BG
    BorderColor COLOR_BOUNDARY_CONTAINER_BD
    BorderStyle dashed
    BorderThickness 1
    Shadowing false
}

!define Container_Package(alias, label) package "==label" <<container package>> as alias
skinparam package<<container package>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_BOUNDARY_CONTAINER_BG
    BorderColor COLOR_BOUNDARY_CONTAINER_BD
    Shadowing false
}

!define Component(alias, label, description=" ", technology="", link="") component "==label\n //description//\n ""technology"" " <<component>> as alias link
skinparam component<<component>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_COMPONENT_BG
    BorderColor COLOR_COMPONENT_BD
    Shadowing false
}

!define Component_PubSub(alias, label, description=" ", technology="", link="") queue "==label\n //description//\n ""technology"" " <<pubsub component>> as alias link
skinparam queue<<pubsub component>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_COMPONENT_BG
    BorderColor COLOR_COMPONENT_BD
    Shadowing false
}

!define Component_Database(alias, label, description=" ", technology="", link="") database "==label\n //description//\n ""technology"" " <<database component>> as alias link
skinparam database<<database component>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_COMPONENT_BG
    BorderColor COLOR_COMPONENT_BD
    Shadowing false
}

!define Component_Storage(alias, label, description=" ", technology="", link="") stack "==label\n //description//\n ""technology"" " <<storage component>> as alias link
skinparam stack<<storage component>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_COMPONENT_BG
    BorderColor COLOR_COMPONENT_BD
    Shadowing false
}

!define Component_Config(alias, label, description=" ", technology="", link="") file "==label\n //description//\n ""technology"" " <<config component>> as alias link
skinparam file<<config component>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_COMPONENT_BG
    BorderColor COLOR_COMPONENT_BD
    Shadowing false
}

' ----------------------------------------------------
' ----------------------------------------------------

@enduml
