@startuml C4-Common

' !include style.puml
!include https://raw.githubusercontent.com/N0N4M3pl/plantuml-C4/master/src/style.puml

' ----------------------------------------------------
' Document
' ----------------------------------------------------

!definelong Header(text)
title text
!enddefinelong

!definelong Footer()
left footer %filename() | %date()
!enddefinelong

!define Note(alias, text, side="right") note side of alias : text
skinparam Note {
    FontColor COLOR_GRAY_4
    BackgroundColor white
    BorderColor COLOR_GRAY_2
}

' ----------------------------------------------------
' Common
' ----------------------------------------------------

!define Person(alias, label, description=" ") actor "==label\n //description//" <<person>> as alias
skinparam actor<<person>> {
    StereotypeFontColor COLOR_FONT_DARK
    FontColor COLOR_FONT_DARK
    BackgroundColor COLOR_PERSON_BG
    BorderColor COLOR_PERSON_BD
    Shadowing false
}

!define Relation(fromAlias, toAlias, direction="--", label="") fromAlias direction toAlias : "label"
skinparam Arrow {
    FontColor COLOR_FONT_DARK
    Color COLOR_RELATION
    FontSize 12
    PathHoverColor COLOR_RED_1
}

' ----------------------------------------------------
' ----------------------------------------------------

@enduml
