@startuml C4-style

' ----------------------------------------------------
' Document
' ----------------------------------------------------

!define LAYOUT_TOP_DOWN top to bottom direction
!define LAYOUT_LEFT_RIGHT left to right direction
!define LINE_STRAIGHT skinparam Linetype ortho

skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam maxMessageSize 150
skinparam PathHoverColor #RED

' ----------------------------------------------------
' Colors
' ----------------------------------------------------

!define COLOR_GRAY_1 #ecf0f1
!define COLOR_GRAY_2 #b6c1c5
!define COLOR_GRAY_3 #84939c
!define COLOR_GRAY_4 #566775
!define COLOR_GRAY_5 #2c3e50

!define COLOR_YELLOW_1 #fffa6f
!define COLOR_YELLOW_2 #f8df46
!define COLOR_YELLOW_3 #f1c40f

!define COLOR_ORANGE_1 #ffe386
!define COLOR_ORANGE_2 #f2b24e
!define COLOR_ORANGE_3 #e67e22

!define COLOR_RED_1 #ffb99c
!define COLOR_RED_2 #f87b57
!define COLOR_RED_3 #eb1e1e

!define COLOR_GREEN_1 #85ffb7
!define COLOR_GREEN_2 #5ee594
!define COLOR_GREEN_3 #2ecc71

!define COLOR_TURQUOISE_1 #93e8ea
!define COLOR_TURQUOISE_2 #63d0d3
!define COLOR_TURQUOISE_3 #1ab9bc

!define COLOR_BLUE_1 #98e1ff
!define COLOR_BLUE_2 #65bded
!define COLOR_BLUE_3 #3498db

' Document
!define COLOR_FONT_DARK COLOR_GRAY_5
!define COLOR_FONT_LIGHT COLOR_GRAY_1

' Common
!define COLOR_BOUNDARY_BG white
!define COLOR_BOUNDARY_BD COLOR_GRAY_2
!define COLOR_PERSON_BG COLOR_GRAY_4
!define COLOR_PERSON_BD COLOR_GRAY_4
!define COLOR_RELATION COLOR_GRAY_4

' Context
!define COLOR_SYSTEM_BG COLOR_GRAY_1
!define COLOR_SYSTEM_BD COLOR_GRAY_4
!define COLOR_SYSTEM_EXTERNAL_BG COLOR_GRAY_1
!define COLOR_SYSTEM_EXTERNAL_BD COLOR_GRAY_2

' Container
!define COLOR_BOUNDARY_SYSTEM_BG COLOR_GRAY_1
!define COLOR_BOUNDARY_SYSTEM_BD COLOR_GRAY_4
!define COLOR_CONTAINER_BG COLOR_BLUE_2
!define COLOR_CONTAINER_BD COLOR_GRAY_4

' Component
!define COLOR_BOUNDARY_CONTAINER_BG COLOR_GRAY_1
!define COLOR_BOUNDARY_CONTAINER_BD COLOR_BLUE_2
!define COLOR_COMPONENT_BG COLOR_GRAY_1
!define COLOR_COMPONENT_BD COLOR_BLUE_3

' ----------------------------------------------------
' ----------------------------------------------------

@enduml