@startuml C4-style

!include colors.puml

' ----------------------------------------------------
' Document
' ----------------------------------------------------

!define LAYOUT_TOP_DOWN top to bottom direction
!define LAYOUT_LEFT_RIGHT left to right direction

skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam maxMessageSize 150

' ----------------------------------------------------
' Views
' ----------------------------------------------------

!define FONT_COLOR COLOR_BLACK
!define FONT_COLOR_LIGHT COLOR_WHITE_LIGHT

' Common
!define BOUNDARY_BG_COLOR white
!define BOUNDARY_BD_COLOR COLOR_WHITE
!define PERSON_BG_COLOR COLOR_BLACK_LIGHT
!define PERSON_BD_COLOR COLOR_BLACK_LIGHT
!define RELATION_COLOR COLOR_BLACK_LIGHT

' Context
!define SYSTEM_BG_COLOR white
!define SYSTEM_BD_COLOR COLOR_BLACK_LIGHT
!define SYSTEM_EXTERNAL_BG_COLOR white
!define SYSTEM_EXTERNAL_BD_COLOR COLOR_GRAY_LIGHT

' Container
!define BOUNDARY_SYSTEM_BG_COLOR COLOR_WHITE_LIGHT
!define BOUNDARY_SYSTEM_BD_COLOR COLOR_BLACK_LIGHT
!define CONTAINER_BG_COLOR COLOR_GRAY_LIGHT
!define CONTAINER_BD_COLOR COLOR_GRAY

' Component
!define BOUNDARY_CONTAINER_BG_COLOR COLOR_WHITE_LIGHT
!define BOUNDARY_CONTAINER_BD_COLOR COLOR_GRAY

' ----------------------------------------------------
' ----------------------------------------------------

@enduml